https://wenku.baidu.com/view/2436fc77aaea998fcd220e3a.html
* 赋值与求值函数
| 函数  | 格式                                             | 说明                   |
| setq  | (setq <变量1> <表达式1> [<变量2> <表达式2> ...]) | 赋值函数               |
| set   | (set <变量> <表达式>)                            | 再赋值函数             |
| quote | (quote (表达式)) 或：`(表达式)                   | 禁止求值函数，符号函数 |
| eval  | (eval <表达式>)                                  | 再求值函数             |
* 数值计算函数
| 函数  | 格式                                        | 说明                        |
| +-*/  | (+ - * / <数1> <数2> ...)                   | 四则运算                    |
| 1+ 1- | (1+ <数>); (1- <数>)                        | <数>加1,或<数>减1的结果     |
| abs   | (abs <数>)                                  | 求<数>的绝对值              |
| sqrt  | (sqrt <数>)                                 | 求<数>的平方根，值为实数    |
| expt  | (expt <底数><幕>)                           | 求数的次方                  |
| exp   | (exp <数>                                   | e的<数>次方                 |
| log   | （log <数>)                                 | exp 的反函数                |
| min   | (min <numb数1er1> <数2>...)                 | 求最小值                    |
| max   | (max <数1> <数2>...)                        | 求最大值                    |
| gcd   | (gcd <数1> <数2>)                           | 求<数1>和<数2>的最大公约数  |
| rem   | (rem <数1> <数2>)                           | 求<数1>和<数2>的余数        |
| sin   | (sin <角>)其单位为弧度                      | 此函数返回 <角> 的正弦值    |
| cos   | (cos <角>)                                  | 此函数返回 <角> 的余弦值    |
| atan  | (atan <数1> [ <数2>])  (atan <数1> <数2>)： | 该函数返回 <数1> 的反正切值 |
* 字符串处理函数
| 函数    | 格式                               | 说明                     |
| strcat  | (strcat <字符串1> <字符串2>…)     | 字符串链接函数           |
| strlen  | (strlen <字符串>)                  | 求字符串长度函数         |
| substr  | (substr <字符串> <开始> [ <长度>]) | 字符串截取子串函数       |
| strcase | (strcase <字符串> [ <表达式> ])    | 字符串大小写转换函数     |
| read    | (read <字符串>)                    | 字符串转换成原子或表函数 |
* 关系运算函数
| =     | (= <表达式1> <表达式2>…)                | 不等于函数     |
| <     | (< <表达式1> <表达式2>…)                | 小于函数       |
| <=    | (<= <表达式1> <表达式2>…)               | 小于或等于函数 |
| >     | (> <表达式1> <表达式2>…)                | 大于函数       |
| >=    | (>= <表达式1> <表达式2>…)               | 大于或等于函数 |
| eq    | (eq <表达式1> <表达式2>)                | 恒等函数       |
| equal | (equal <表达式1> <表达式2> [ <误差值> ]) | 等值函数       |
* 逻辑运算函数
|and|(and <表达式1> <表达式2>…)|逻辑与函数|
|or|(or <表达式1> <表达式3>…)|逻辑或函数|
|not|(not <表达式>)|逻辑非函数|
* 几何函数
| angle                                                 | (angle <点1> <点2>)                       | 求角度函数   |
| distance                                              | (distance <点1> <点2>)                    | 求距离函数   |
| polar                                                 | (polar <中心点> <方位角> <距离>)          | 求坐标点函数 |
| inters                                                | (inters <点1> <点2> <点3> <点4> [<方式>]) | 求交点函数   |
| osnap                                                 | (osnap <点> <方式名>)                     | 目标捕捉函数 |
| “Nea”、“Mid”、“endp”、“cen”、“tan”和“per”|
* 数字、字符串转换函数
| ascii  | (ascii <字符串>)             | 字符转换成ASCII 码整数函数 |
| atof   | (atof <字符串>)              | 数字串转换成实数函数       |
| atoi   | (atoi <字符串>)              | 数字串转换成整数函数       |
| chr    | (chr <整数>)                 | ASCII 码转换成字符串函数   |
| itoa   | (itoa <整数> )               | 整数转换成字符串函数       |
| float  | (float <数>)                 | 整型数转换成实型数函数     |
| fix    | (fix <数>)                   | 截尾取整函数               |
| angtos | (angtos <角> <方式> <精度> ) | 角度转换成字符串函数       |
0十进制度格式; 1度/分/秒格式; 2公制格式(1g=0.9d); 3弧度格式; 4测量者单位格式
| rtos | (rtos <数> <方式> <精度>) | 数转换成数字串函数 |
1科学计数格式; 2十进制格式; 3工程计数格式; 4建筑计数格式  5分数单位格式
* 表处理函数
| list      | (list <表达式>…)                     | 构造新表函数             |
| car       | (car <表>)                            | 取表头函数               |
| cdr       | (cdr <表>)                            | 取表尾函数               |
| cadr      | (cadr <表>)                           | 取表第二元素函数         |
| last      | (last <表>)                           | 取表最后一个元素函数     |
| append    | (append <表>…)                       | 构造新表函数             |
| cons      | (cons <表达式1> <表达式2>)            | 新元素加入表函数         |
| reverse   | (reverse <表>)                        | 颠倒表元素顺序函数       |
| nth       | (nth <n> <表>)                        | 取表第n 个元素函数       |
| length    | (length <表>)                         | 求表元素个数函数         |
| subst     | (subst <新项> <老项> <表>)            | 替换表中元素函数         |
| assoc     | (assoc <关键字> <联结表>)             | 检索表中元素函数         |
| get       |                                       | 族交互式输入函数         |
| getint    | (getint [ <提示>])                    | 输入整型数函数           |
| getreal   | (getreal [ <提示> ] )                 | 输入实型数函数           |
| getstring | (getstring [T] [ <提示>])             | 输入字符串函数           |
| getpoint  | (getpoint [<提示>])                   | 输入点函数               |
| getdist   | (getdist [<点>] [<提示>])             | 输入距离函数             |
| getangle  | (getangle [<点>][<提示>])             | 输入角度函数             |
| getcorner | (getcorner [ <点> ] [ <提示> ])       | 输入窗口点函数           |
| getorient | (getorient [ <点> ] [ <提示> ])       | 输入方位角函数           |
| initget   | (initget [ <控制码> ] [ <限制字符> ]) | 限制输入类型和关键字函数 |
<控制码> 控制意义如下：1——拒绝接受空输入(直接回车或空格)；2——拒绝接受零值；4——拒绝接受负值8——不检查作图限定范围；16——返回三维点32——用虚线(或其他醒目线)画橡筋线
| getkword | (getkword [ <提示> ]) | 输入关键字函数 |
| pause    |                       | 命令暂停函数   |
| command  |                       |                |
* 屏幕操作函数
| graphscr    | (graphscr)                             | 文本屏幕转换到图形屏幕函数 |
| textscr     | (textscr)                              | 图形屏幕转换到文本屏幕函数 |
| redraw      | (redraw [ <实体名> ] [ <方式> ])       | 重画屏幕函数               |
| grclear     | (grclear)                              | 清除图形屏幕函数           |
| vports      | (vports)                               | 视窗说明函数               |
| load        | (load <文件名> [ <错误提示串> ])       | 文件装入函数               |
| prompt      | (prompt <信息>)                        | 字符串显示函数             |
| terpri      | (terpri)                               | 换行函数                   |
| open        | (open <文件名> <方式> )                | 打开文件函数               |
| close       | (close <文件描述符>)                   | 关闭文件函数               |
| print       | (print <表达式>[ <文件描述符>])        | 打印、显示函数             |
| prin1       | (prinl <表达式> [ <文件描述符> ])      | 打印、显示函数             |
| princ       | (princ <表达式> [ <文件描述符> ])      | 打印、显示函数             |
| read-line   | (read-line [ <文件描述符> ])           | 读入行函数                 |
| read-char   | (read－char [ <文件描述符> ])          | 读入字符函数               |
| write－line | (write－line <字符串>[ <文件描述符> ]) | 写入行函数                 |
| write-char  | (write-char <数> [ <文件描述符> ])     | 写入字符函数               |
| getvar      | (getvar <系统变量名> )                 | 查看系统变量函数           |
| setvar      | (setvar <系统变量名> <值>)             | 设置系统变量函数           |
* 条件函数与循环函数
| atom    | (atom <项>)                                                        | 测试是否为原子函数   |
| boundp  | (boundp <符号原子> )                                               | 测试原子是否有值函数 |
| null    | (null <项>)                                                        | 测试是否为空表函数   |
| numberp | (numberp <项>)                                                     | 测试是否为数函数     |
| zerop   | (zerop <项>)                                                       | 测试是否为0 函数     |
| minusp  | (minusp <项>)                                                      | 测试是否为负数函数   |
| listp   | (listp <项>)                                                       | 测试是否为表函数     |
| member  | (member <表达式> <表>)                                             | 测试从属关系函数     |
| type    | (type <项>)                                                        | 测试数据类型函数     |
| if      | (if <条件> <表达式1>[<表达式2>])                                   | 单分支条件函数       |
| cond    | (cond(<条件1> <表达式1>)(<条件2> <表达式2>)……(<条件n><表达式n>)) | 多分支条件函数       |
| progn   | (progn <表达式>…)                                                 | 顺序控制函数         |
| repeat  | (repeat <数> <表达式>…)                                           | 按给定次数循环函数   |
| while   | (while <条件><表达式>…)                                           | 按给定条件循环函数   |
* 嵌套函数
| apply   | (apply <函数> <表>)                                        |                |
| mapcar  | (mapcar <函数><表1>……<表n>)                              |                |
| foreach |                                                            | 形参赋值函数   |
| defun   | (defun <函数名> <参数表><表达式1><表达式2><……><表达式n>) | 自定义函数     |
| lambda  | (lambda <自变量> <表达式> …)                              | 自定义匿名函数 |
* 图形数据库操作函数
| ssget    | (ssget [ <方式> ] [ <点1> ] [ <点2> ] [ <点表> ]) | 选择集构造函数               |
| sslength | (sslength <ss1>)                                  | 求选择集长度的函数           |
| ssname   | (ssname <选择集> <序号>)                          | 实体名检索函数               |
| ssadd    | (ssadd [ <实体名> ] [ <选择集> ])                 | 向选择集中加入新实体函数     |
| ssdel    | (ssdel <实体名> <选择集>)                         | 从选择集中移出实体函数       |
| ssmemb   | (ssmemb <实体名> <选择集>)                        | 测试实体是否在选择集中的函数 |
* 实体名操作函数
| entnext | (entnext [ <实体名> ]) | 实体名搜索函数               |
| entlast | (entlast)              | 获得最后一个主实体名函数     |
| entsel  | (entsel [ <提示>])     | 选择任一实体函数             |
| handent | (handent <实体标号>)   | 实体标号处理函数             |
| entget  | (entget <实体名>)      | 获得实体数据函数             |
| entmod  | (entmod <实体数据表>)  | 修改实体在图形数据中定义函数 |
| entmake | (entmake <实体数据表>) | 生成新实体函数               |
| entdel  | (entdel <实体名>)      | 更新复杂实体屏幕图形函数     |
* 符号表访问函数
| tblnext   | (tblnext <表名> [ <s>] )          | 符号表搜索函数tblsearch |
| tblsearch | (tblsearch <表名> <符号名> [<s>]) | 访问符号表某一项函数    |
